[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/crear-pago"
  to = "/.netlify/functions/crear-pago"
  status = 200
  force = true

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true
